### ISSUE TITLE
about the password of the host login page

### ISSUE THREAD

**Issue by AICrazyyy** [awtrix/AWTRIX-Pro#1]
Hello, I downloaded the stable version of awtrix.jar. When I log in to the webpage [IP: 7000], I am required to enter the password, but I don't know what the password is.

Could you please tell me where to find the password?
![image](https://user-images.githubusercontent.com/17903073/76399812-3dcaf700-63ba-11ea-88f0-06780d0a277b.png)

**Comment by Blueforcer** [comment]
Thats not the right repository for that;)
